### ISSUE TITLE
hyde Error occured when calling meta

### ISSUE THREAD

**Issue by gustavorabello** [gustavorabello/site-gesar#9]
@gcpeixoto Peixoto, please, verify your last commit since I get meta data error when "hyde gen". If you need extra information do  "hyde -vvv gen".

[air] gesar-site >> hyde gen
 21:07:39 hyde.engine Reading site configuration from [/Users/gustavo/projects/python/gesar-site/site.yaml]
 21:07:39 hyde.engine Reading site contents
 21:07:39 hyde.engine Generating site at [/Users/gustavo/projects/python/gesar-site]
 21:07:39 hyde.engine Configuring the template environment
 21:07:39 hyde Error occured when calling meta

**Comment by gcpeixoto** [comment]
Solved!
